### ISSUE TITLE
Update `metacontroller-operator` manifests

### ISSUE THREAD

**Issue by misohu** [canonical/metacontroller-operator#110]
### Context

Each charm has a set of manifest files that have to be upgraded to their target version. The process of upgrading manifest files usually means going to the component’s upstream repository, comparing the charm’s manifest against the one in the repository and adding the missing bits in the charm’s manifest.

### What needs to get done

https://docs.google.com/document/d/1a4obWw98U_Ndx-ZKRoojLf4Cym8tFb_2S7dq5dtRQqs/edit?pli=1#heading=h.jt5e3qx0jypg

### Definition of Done

1. Manifests are updated 
2. Upstream image is used

**Comment by DnPlas** [comment]
Based in [upstream](https://github.com/kubeflow/manifests/tree/v1.9-branch/contrib/metacontroller) Kubeflow, this component hasn't changed for a while, but in the `metacontroller` upstream we have v4.x already.

**Comment by misohu** [comment]
Just for sure I double checked the manifests ... they are the same as we use in charm ...The current difference is that upstream uses image: 
```
docker.io/metacontrollerio/metacontroller:v2.0.4
```

While we are using 
```
docker.io/metacontrollerio/metacontroller:v3.0.0
```

The reason we use 3.0.0 is that we need to use `DecoratorController` object in Reasource Dispatcher. 

There is also [version 4](https://github.com/metacontroller/metacontroller/releases/tag/v4.0.0) released for metacontroller which may be fine for our product. For now we have decided to stick with v3.0.0 for 1.9

**Comment by DnPlas** [comment]
Closing as there is not going to be updated for Kubeflow 1.9. The team has decided to not bump this charm, so we'll have to wait for next release. Closing for now.
