### ISSUE TITLE
Charm hasn't a configurable image 

### ISSUE THREAD

**Issue by orfeas-k** [canonical/metacontroller-operator#80]
### Bug Description

It looks like this charm hasn't a configurable image. It doesn't deduce image from its [metadata.yaml](https://github.com/canonical/metacontroller-operator/blob/584cf1d9d79af1550ef64e9e5744dc2f3faa445d/metadata.yaml) like most of our charms but rather has this hardcoded in its code [here](https://github.com/canonical/metacontroller-operator/blob/89de8ca8dc0ae2452283164ea4a721839379fcf2/src/charm.py#L55).

### To Reproduce

This goes for all environment but creates an issue only when we want to pull the image from another registry e.g. in airgap environment
1. Create airgap environment (https://github.com/canonical/bundle-kubeflow/pull/682) with metacontroller as the only image
2. Deploy metacontroller with `juju deploy ./<path-to-local-metacontroller-charm> --trust`

### Environment

Airgapped 

### Relevant log output
`microk8s kubectl logs -n kubeflow metacontroller-operator-charm-0`
```shell
Error from server (BadRequest): container "metacontroller" in pod "metacontroller-operator-charm-0" is waiting to start: image can't be pulled
```
`microk8s kubectl describe pod -n kubeflow metacontroller-operator-charm-0`
```shell
Events:
  Type    Reason   Age                    From     Message
  ----    ------   ----                   ----     -------
  Normal  BackOff  4m40s (x251 over 64m)  kubelet  Back-off pulling image "docker.io/metacontrollerio/metacontroller:v3.0.0"
```

**Comment by kimwnasptd** [comment]
Linking to https://github.com/canonical/bundle-kubeflow/issues/680 as well
